plugins:
  - jekyll-relative-links

theme: jekyll-theme-minimal

relative_links:
  enabled: true
  collections: true

include:
  - index.md
  - chain_factory_spec_003.md
  - chain_factory_spec_002.md
  - chain_factory_spec_001.md
